title: Mykyta Zaikin
logo: /images/DSC_0837.jpg

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Short intro
  <br><br>
  Microsoft Certified: Azure Data Scientist Associate, Azure AI Fundamentals
  <br><br>
  <a href="https://www.credly.com/users/mykyta-zaikin">My Azure cerifficates</a> 
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'