title: Mykyta Zaikin
logo: /assets/img/DSC_0837.jpg

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Short intro
  <br><br>
  Additional info
  <br><br>
  Certifications
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
